"""
Patient Screening Filter Model

Represents reusable filter templates for patient screening.
Filters define criteria for including/excluding patients from cohorts.
"""

from sqlalchemy import Column, String, Text, Integer, Boolean, CheckConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship

from app.models.tenant.patient_screening.base import Base, UUIDPrimaryKey, TimestampMixin


class Filter(Base, UUIDPrimaryKey, TimestampMixin):
    """
    Patient Screening Filter Model.

    Represents a saved filter configuration that can be:
    - Reused across multiple cohorts
    - Marked as a template for common screening criteria
    - Generated by AI from natural language

    Filter Structure (JSONB):
    {
        "id": "uuid",
        "name": "Filter Name",
        "logic": "AND" | "OR",
        "negate": false,
        "rules": [
            {
                "type": "rule",
                "id": "uuid",
                "field": "column_name",
                "operator": "equals" | "gte" | "lte" | "contains" | "between" | ...,
                "value": "value" | ["value1", "value2"]
            },
            {
                "type": "group",
                "id": "uuid",
                "name": "Sub-group",
                "logic": "AND" | "OR",
                "negate": false,
                "rules": [...]
            }
        ]
    }

    Attributes:
        id: UUID primary key
        name: Filter name (required, min 1 char)
        description: Optional filter description
        filter: FilterGroup structure as JSONB
        is_template: Whether this is a system/shared template
        usage_count: Number of cohorts using this filter
        created_by: Auth0 user ID who created the filter
        created_at: Creation timestamp
        updated_at: Last update timestamp
    """
    __tablename__ = "patient_screening_filters"

    # Basic Information
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)

    # Filter Configuration
    filter = Column(JSONB, nullable=False)  # FilterGroup structure

    # Metadata
    is_template = Column(Boolean, default=False)  # System/shared template
    usage_count = Column(Integer, default=0)  # Track cohort references

    # Audit Fields
    # Note: enterprise_id removed - handled by schema-based multi-tenancy
    created_by = Column(String(255), nullable=False)

    # Relationships
    cohorts = relationship(
        "Cohort",
        back_populates="saved_filter",
        lazy="selectin"
    )

    # Constraints
    __table_args__ = (
        CheckConstraint(
            "jsonb_typeof(filter) = 'object'",
            name="ps_filters_valid_filter"
        ),
        CheckConstraint(
            "char_length(name) >= 1",
            name="ps_filters_valid_name"
        ),
    )

    def __repr__(self):
        return f"<Filter(id={self.id}, name='{self.name}', is_template={self.is_template})>"
