"""Add user_media table for profile photos

Revision ID: 583cacebc8ce
Revises: 1f6cc0ffc441
Create Date: 2025-10-23 09:07:41.103127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583cacebc8ce'
down_revision = '1f6cc0ffc441'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_media',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.Enum('PROFILE_PHOTO', 'COVER_PHOTO', name='usermediatype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_media_deleted_at'), 'user_media', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_media_id'), 'user_media', ['id'], unique=False)
    op.create_index(op.f('ix_user_media_user_id'), 'user_media', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_media_user_id'), table_name='user_media')
    op.drop_index(op.f('ix_user_media_id'), table_name='user_media')
    op.drop_index(op.f('ix_user_media_deleted_at'), table_name='user_media')
    op.drop_table('user_media')
    # ### end Alembic commands ###