"""Add master data

Revision ID: 59c815d8aa17
Revises: 8e15be95a40f
Create Date: 2025-09-25 10:44:26.576302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c815d8aa17'
down_revision = '8e15be95a40f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_data',
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('parent_scope', sa.String(length=100), nullable=True),
    sa.Column('parent_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'code', name='uq_master_data_scope_code')
    )
    op.create_index(op.f('ix_master_data_code'), 'master_data', ['code'], unique=False)
    op.create_index(op.f('ix_master_data_id'), 'master_data', ['id'], unique=False)
    op.create_index(op.f('ix_master_data_is_active'), 'master_data', ['is_active'], unique=False)
    op.create_index(op.f('ix_master_data_parent_code'), 'master_data', ['parent_code'], unique=False)
    op.create_index(op.f('ix_master_data_parent_scope'), 'master_data', ['parent_scope'], unique=False)
    op.create_index(op.f('ix_master_data_scope'), 'master_data', ['scope'], unique=False)
    op.create_table('master_data_locale',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id', 'locale', name='uq_master_data_locale_master_locale')
    )
    op.create_index(op.f('ix_master_data_locale_id'), 'master_data_locale', ['id'], unique=False)
    op.create_index(op.f('ix_master_data_locale_locale'), 'master_data_locale', ['locale'], unique=False)
    op.create_index(op.f('ix_master_data_locale_master_id'), 'master_data_locale', ['master_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_data_locale_master_id'), table_name='master_data_locale')
    op.drop_index(op.f('ix_master_data_locale_locale'), table_name='master_data_locale')
    op.drop_index(op.f('ix_master_data_locale_id'), table_name='master_data_locale')
    op.drop_table('master_data_locale')
    op.drop_index(op.f('ix_master_data_scope'), table_name='master_data')
    op.drop_index(op.f('ix_master_data_parent_scope'), table_name='master_data')
    op.drop_index(op.f('ix_master_data_parent_code'), table_name='master_data')
    op.drop_index(op.f('ix_master_data_is_active'), table_name='master_data')
    op.drop_index(op.f('ix_master_data_id'), table_name='master_data')
    op.drop_index(op.f('ix_master_data_code'), table_name='master_data')
    op.drop_table('master_data')
    # ### end Alembic commands ###