"""Added guest role model

Revision ID: 212220ddb4b2
Revises: e8ea8b0ce64f
Create Date: 2025-09-30 13:22:21.395476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212220ddb4b2'
down_revision = 'e8ea8b0ce64f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_roles',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id', 'role_id', name='uq_guest_role')
    )
    op.create_index(op.f('ix_guest_roles_id'), 'guest_roles', ['id'], unique=False)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_guest_roles_id'), table_name='guest_roles')
    op.drop_table('guest_roles')
    # ### end Alembic commands ###